#!/usr/bin/bash
export PGPASSWORD=$IG_PASSWD_FILE

#Create image gallery user
#psql -h $PG_HOST -U postgres -p $PG_PORT -d $IG_DATABASE -c "create user image_gallery with password '"$IG_PW"';"

#Run DB setup with image gallery user
psql -h $PG_HOST -U image_gallery -d $IG_DATABASE -p $PG_PORT < db/setup.sql
