#!/usr/bin/bash

if [ -f "$IG_PASSWD_FILE" ]; then
  $IG_PASSWD = `cat $IG_PASSWD_FILE`
fi

export PGPASSWORD=$IG_PASSWD

#Create image gallery user
#psql -h $PG_HOST -U postgres -p $PG_PORT -d $IG_DATABASE -c "create user image_gallery with password '"$IG_PW"';"

#Run DB setup with image gallery user
psql -h $PG_HOST -U $IG_USER -d $IG_DATABASE -p $PG_PORT < db/setup.sql
