#!/usr/bin/bash

if [ $# != "1" ]; then
    echo "Usage: deploy <version-number>"
    exit 1
fi

aws s3 cp ec2-scripts/ec2-prod-$1.sh s3://edu.au.cc.dam0045.image-gallery-config
aws s3 cp nginx s3://edu.au.cc.dam0045.image-gallery-config --recursive
